'use client'

import Link from 'next/link'
import { useMemo, useState } from 'react'
import { useRouter } from 'next/navigation'
import { ArrowRight, BookOpen, KeyRound } from 'lucide-react'
import { supabaseBrowser } from '@/lib/supabaseBrowser'

export default function ResetPasswordPage(){const router=useRouter();const supabase=useMemo(()=>supabaseBrowser(),[]);const[password,setPassword]=useState('');const[password2,setPassword2]=useState('');const[status,setStatus]=useState('');const[loading,setLoading]=useState(false);async function update(){setStatus('');if(password.length<8){setStatus('新密码至少需要 8 位。');return}if(password!==password2){setStatus('两次输入的新密码不一致。');return}setLoading(true);try{const{error}=await supabase.auth.updateUser({password});if(error){setStatus(`修改失败：${error.message}`);return}setStatus('密码已更新，正在返回登录页…');setTimeout(()=>router.replace('/login'),800)}finally{setLoading(false)}}return <main className="auth-page"><aside className="auth-aside"><Link href="/" className="landing-brand"><span><BookOpen size={19}/></span><strong>MAPer</strong><small>学习平台</small></Link><div className="auth-aside__copy"><span>账户安全</span><h1>设置一个新的登录密码</h1><p>需要通过邮箱中的重置链接进入本页面。修改完成后，使用新密码重新登录。</p></div></aside><section className="auth-main"><div className="auth-main__top"><Link className="button button--secondary" href="/login">返回登录</Link></div><div className="auth-card"><KeyRound size={28}/><h2>重置密码</h2><p>建议使用至少 8 位、容易记住但不易猜测的密码。</p><div className="form-field"><label htmlFor="password">新密码</label><input id="password" type="password" placeholder="至少 8 位" value={password} onChange={e=>setPassword(e.target.value)} autoComplete="new-password"/></div><div className="form-field"><label htmlFor="password2">确认新密码</label><input id="password2" type="password" placeholder="再次输入新密码" value={password2} onChange={e=>setPassword2(e.target.value)} autoComplete="new-password"/></div><button className="button button--primary auth-submit" onClick={update} disabled={loading}>{loading?'正在更新…':<>更新密码 <ArrowRight size={17}/></>}</button>{status?<div className="auth-status">{status}</div>:null}</div></section></main>}
