'use client'

import Link from 'next/link'
import { useEffect, useMemo, useState } from 'react'
import { BookOpen, Check, CircleHelp, LogOut, Palette, RefreshCw, Save, ShieldCheck, UserRound } from 'lucide-react'
import { supabaseBrowser } from '@/lib/supabaseBrowser'
import { applyTheme, THEME_STORAGE_KEY, type ThemeKey } from '@/components/ThemeProvider'

type Profile = { user_id:string;role:string|null;username:string|null;nickname:string|null;bio:string|null;avatar_key:string|null;username_updated_at:string|null;is_banned:boolean;is_muted:boolean;muted_until:string|null }
const avatars=[{key:'default_1',label:'蓝色',color:'#315c87'},{key:'default_2',label:'绿色',color:'#496b5c'},{key:'default_3',label:'红色',color:'#a54b4b'},{key:'default_4',label:'青色',color:'#176b74'}]
const themes:Array<{key:ThemeKey;name:string;color:string}>=[{key:'quiet-blue',name:'静谧蓝',color:'#315c87'},{key:'sage',name:'鼠尾草绿',color:'#496b5c'},{key:'graphite',name:'石墨红',color:'#a54b4b'},{key:'clear-teal',name:'清透青',color:'#176b74'}]

export default function MePage(){
  const supabase=useMemo(()=>supabaseBrowser(),[])
  const[loading,setLoading]=useState(true);const[saving,setSaving]=useState(false);const[status,setStatus]=useState('')
  const[email,setEmail]=useState('');const[uid,setUid]=useState('');const[role,setRole]=useState<string|null>(null)
  const[username,setUsername]=useState('');const[nickname,setNickname]=useState('');const[bio,setBio]=useState('');const[avatarKey,setAvatarKey]=useState('default_1')
  const[theme,setTheme]=useState<ThemeKey>(()=>typeof window==='undefined'?'quiet-blue':((localStorage.getItem(THEME_STORAGE_KEY)as ThemeKey|null)??'quiet-blue'));const[accountState,setAccountState]=useState('正常')
  async function load(){try{const{data:s}=await supabase.auth.getSession();const user=s.session?.user;if(!user)return;setEmail(user.email??'');setUid(user.id);const{data:p}=await supabase.from('user_profiles').select('user_id,role,username,nickname,bio,avatar_key,username_updated_at,is_banned,is_muted,muted_until').eq('user_id',user.id).maybeSingle();if(p){const profile=p as Profile;setRole(profile.role);setUsername(profile.username??'');setNickname(profile.nickname??'');setBio(profile.bio??'');setAvatarKey(profile.avatar_key??'default_1');setAccountState(profile.is_banned?'已停用':profile.is_muted?'受限':'正常')}}finally{setLoading(false)}}
  useEffect(()=>{void load()
    // Profile loading is intentionally tied to this stable Supabase client.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  },[supabase])
  async function save(){if(!uid)return;setSaving(true);setStatus('');try{const payload={username:username.trim().toLowerCase()||null,nickname:nickname.trim(),bio:bio.trim(),avatar_key:avatarKey};const{error}=await supabase.from('user_profiles').update(payload).eq('user_id',uid);if(error)throw error;setStatus('个人资料已保存。');await load()}catch(error){const message=error instanceof Error?error.message:'未知错误';setStatus(message.includes('30 days')?'用户名 30 天内只能修改一次。':`保存失败：${message}`)}finally{setSaving(false)}}
  async function signOut(){await supabase.auth.signOut();window.location.href='/'}
  return <main className="workspace-page profile-page"><div className="workspace-heading"><div><span className="page-eyebrow">账户与偏好</span><h1>个人中心</h1><p>管理公开资料、学习外观和账户状态。</p></div><button className="button button--secondary" onClick={signOut}><LogOut size={16}/>退出登录</button></div>{status?<div className="admin-notice">{status}</div>:null}<div className="profile-layout"><div className="profile-main"><section className="panel"><div className="panel-heading"><div><h2>个人资料</h2><p>昵称会显示在学习首页和顶部栏</p></div><UserRound size={19}/></div>{loading?<div className="ui-status">正在加载资料…</div>:<><div className="avatar-picker">{avatars.map(item=><button key={item.key} className={avatarKey===item.key?'is-selected':''} onClick={()=>setAvatarKey(item.key)}><i style={{background:item.color}}><UserRound size={18}/></i><span>{item.label}</span>{avatarKey===item.key?<Check size={15}/>:null}</button>)}</div><div className="admin-form-grid profile-form"><label>昵称<input value={nickname} onChange={e=>setNickname(e.target.value)} placeholder="用于学习平台内显示"/></label><label>用户名<input value={username} onChange={e=>setUsername(e.target.value)} placeholder="小写字母、数字或下划线"/></label><label className="is-full">个人简介<textarea rows={5} value={bio} onChange={e=>setBio(e.target.value)} placeholder="写下一句提醒自己持续学习的话。"/></label></div><button className="button button--primary" onClick={save} disabled={saving}><Save size={16}/>{saving?'正在保存…':'保存资料'}</button></>}</section><section className="panel"><div className="panel-heading"><div><h2>外观配色</h2><p>只改变颜色，不改变页面位置和操作逻辑</p></div><Palette size={19}/></div><div className="profile-themes">{themes.map(item=><button key={item.key} className={theme===item.key?'is-selected':''} onClick={()=>{setTheme(item.key);applyTheme(item.key)}}><i style={{background:item.color}}/><span>{item.name}</span>{theme===item.key?<Check size={16}/>:null}</button>)}</div></section></div><aside className="profile-side"><section className="panel account-card"><div className="account-avatar" style={{background:avatars.find(a=>a.key===avatarKey)?.color}}><UserRound size={26}/></div><h2>{nickname||username||email.split('@')[0]}</h2><p>{email}</p><dl><div><dt>账户状态</dt><dd>{accountState}</dd></div><div><dt>权限</dt><dd>{role==='owner'?'Owner':role==='admin'?'管理员':'学习者'}</dd></div><div><dt>用户 ID</dt><dd>{uid?`${uid.slice(0,8)}…`:'—'}</dd></div></dl></section><section className="panel profile-links"><Link href="/onboarding?replay=1"><span><CircleHelp size={18}/><i><strong>重新查看新手教程</strong><small>课程、答题与错题流程</small></i></span></Link><Link href="/courses"><span><BookOpen size={18}/><i><strong>返回我的课程</strong><small>继续上次学习</small></i></span></Link>{role==='owner'||role==='admin'?<Link href="/admin"><span><ShieldCheck size={18}/><i><strong>进入管理后台</strong><small>维护课程和平台内容</small></i></span></Link>:null}<button onClick={load}><span><RefreshCw size={18}/><i><strong>重新加载资料</strong><small>同步最新账户状态</small></i></span></button></section></aside></div></main>
}
